<script lang="ts">
    import { base } from "$app/paths";
    import ExpressionBox from "../../../components/expressionbox/ExpressionBox.svelte";
    import BackgroundTitle from "../../../components/titlebar/BackgroundTitle.svelte";
</script>

<div class="margins">
    <section>
        <BackgroundTitle title="Physically Accurate (F=MA) Physics Gun" background='{base}/assets/expression2/physgun/banner.jpg'/>
        <section class="extra-space" style="min-height: 306pt">
            <img 
                src="{base}/assets/expression2/physgun/physgun-1.jpg" 
                style="float:right; max-height: 306pt; margin-right: 0px;"
                alt="The Physics Gun Beam supporting a player's weight."
            >
            This was just a massive 'what if' project constructed to put to rest
            some thought experiments involving the behavior of the Physics Gun in real life.<br>
            <br>
            The 'what if' was this: <i>What if the physics gun actually obeyed classical newtonian physics?</i><br>
            <br>
            The way it behaves by default in unmodded sandbox, the physics gun violates Newton's Third Law, 
            because a player lifting/moving an object does not feel the "equal and opposite" force that would usually be
            generated by such an action. This allows for techniques such as prop flying, where players can fly 
            at immense speeds by standing on objects and lifting them.  Some may find this entertaining, but
            I see it as a physics atrocity.  If this worked in real life, we'd already be visiting
            other star systems by now!  I had to do something.<br>
            <br>
            With a little vector math, calculus, and quaternion magic, I was able to rework
            the physics gun—adding back the neglected reaction forces and coupling held objects
            to the player.  The results of this were extremely entertaining—I discovered several
            new physically accurate tricks and gimmicks that weren't possible with the stock
            physics gun.  Such features included wedging myself between walls, scaling 
            buildings with hook-shaped props, and even using the inertia of heavy props to 
            fling myself around the map.<br>
            <br>
            I currently have an unscripted showcase of this E2 on <a href="https://www.youtube.com/watch?v=58QzMv1wG7Y">Mee's YouTube channel</a>.  
            Since the beginning of my Garry's Mod server, he's been a friend of mine for a while now.<br>
            <br>
            I'll be posting a scripted, more organized showcase on my channel Soon&trade;.<br>
            <br>
            Special thanks to <a href="https://discord.com/users/347893446897434624/">@Jacbo</a> for
            providing me the <i>pointVel</i> function, which was necessary to make prop rotation work
            correctly.  I have not yet taken linear algebra :&rpar;
        </section>
        <ExpressionBox 
            source="https://raw.githubusercontent.com/Fasteroid/expression2-public/master/physgun_two-way_coupling.txt"
            name="vr-holo-designer"
        />
    </section>
</div>
